name: Build iOS IPA

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest  # Usa un runner con macOS
    steps:
      - uses: actions/checkout@v4

      # Configura Java y Kotlin
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Configura Xcode (necesario para compilar para iOS)
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      # Asegura permisos para gradlew
      - name: Set gradlew permissions
        run: chmod +x ./gradlew

      # Compila el framework de KMP
      - name: Build KMP for iOS
        run: ./gradlew :shared:linkReleaseFrameworkIosArm64

      # Genera el .xcarchive y .ipa usando Xcode
      - name: Archive and Export IPA
        run: |
          xcodebuild archive \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -configuration Release \
            -archivePath iosApp.xcarchive \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS

          xcodebuild -exportArchive \
            -archivePath iosApp.xcarchive \
            -exportPath ./output \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
          
      # Sube el .ipa como artifact (opcional)
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ./output/YourApp.ipa
          if-no-files-found: error  # Opcional: falla si no hay .ipa
