name: Build iOS (KMM)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Show directory structure
        run: ls -R
        
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: |
          cd mykmmapp/iosApp
          pod install

      - name: Build .ipa
        run: |
          cd mykmmapp/iosApp
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/iosApp.xcarchive \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/iosApp.xcarchive \
            -exportPath $PWD/build/export \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iosApp.ipa
          path: iosApp/build/export/*.ipa
